services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "15432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backends

  fastapi:
    image: python:3.12-slim
    command: "sh -c 'poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'"
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8888:8000"
    volumes:
      - ./server:/app
    networks:
      - backends

volumes:
  data:
  app:


networks:
  backends:
    driver: bridge
